fixed previous PR for team 4941
firstwiki/frc4000 pull request #8
Opened 2017-02-10 18:33 UTC by dvtate

The links are no longer wrapped in <a> tags.
I think this is all I needed to change. If there's any other recommendations/requirements please tell me (I'll probably be updating this further after build season).

2017-02-10 18:35 UTC, virtuald requested changes

2017-02-10 18:35 UTC, virtuald commented on _frc/4900/4941.md
> +    Twitter(@FRC4941): https://twitter.com/FRC4941
Yeah... so this part of the file is YAML, so it has to be strictly formatted. It should be `Twitter:`

2017-02-10 18:35 UTC, virtuald commented on _frc/4900/4941.md
> +  2014 - 2015:
Same thing here, 2014-2015 isn't a valid YAML key, just use a single parameter.

Maybe in the summer we'll make this easier to do, sorry about that!

2017-02-11 21:24 UTC, dvtate commented on _frc/4900/4941.md
> +  2014 - 2015:
Would having different names for the parts of the code be allowed as is done here?
```
  2017:
  - Main-Robot:
    - https://github.com/robobibb/main-bot-2017
    - C++
  - Practice-Robot:
    - https://github.com/robobibb/test-bot-2017
    - C++
```

2017-02-11 22:57 UTC, closed without merging

2017-02-11 22:57 UTC, virtuald commented
I went ahead and fixed the formatting for you and pushed it in a separate commit.

2017-02-12 03:04 UTC, dvtate commented
Ok thx